### ISSUE TITLE
Migrationlar stabilize edildi.

### ISSUE THREAD

**Issue by ashkan90** [bdemirpolat/Stilo-Backend#4]
Beego nun kaynak kodunu inceledikten sonra projemizdeki bug ını giderdim.
Hazırlanan migration, kendi kendisine SQL yazamıyor. Bizim son satıra kadar yazdığımız kodlar arka tarafta SQL'e yorumlanıyor ama işlenmiyor, yani hazırlanıyor.
Şöyle ki,
```go
m.CreateTable("replies", "INNODB", "utf8")
```
bu satır arka tarfata şöyle birşeye tekamül ediyor diyebilirim;
```go
var preparingSql string
func init() {
    preparingSql = ""
}
func CreateTable(name string, engine string, cCode string) {
     preparingSql = "CREATE TABLE `" + name + "`" + "(<someToken>) ENGINE=" + engine + " DEFAULT CHARSET=" + cCode
}
```

yazdığımız her kod, arka tarfata plain text olarak tutuluyor. Kısacası Execute edilen bir SQL yok. 
SQL in execute edilmesi için bizim, Migration struct ının 'SQL' fieldına, tüm bu yazdığımız plain SQL i aktarmamız gerekiyor. O da bu şekilde oluyor.

```go
...
sql := m.GetSQL()
m.SQL(sql)
....
```

Bu aşamada, beego'nun yazdığı migration u çalıştırarak plainSql i çalıştırabiliriz.
```cmd
bee migrate -driver=mysql -conn={username}:{password}@tcp(127.0.0.1:3306)/{dbName}
```

orijinali: 
```cmd
bee migrate -driver=mysql -conn=root@tcp(127.0.0.1:3306)/stilo
```

Olay bu kadar. olurda tabloları rollback yaptırmak istersek, 
```cmd
bee migrate rollback -driver=mysql -conn=root@tcp(127.0.0.1:3306)/stilo
```

**Comment by bdemirpolat** [comment]
Bir önceki versiyonda zaten m.SQL implementasyonu vardı commitlere baktığımda hatırladım fakat bazı tablolar eklenirken bazı tablolar eklenmiyor ve hata çıktısı 'nil' şeklindeydi. Senin cihazında m.SQL fonksiyonu tüm tabloları işledi mi?

**Comment by ashkan90** [comment]
tüm tablolar sorunsuz ekleniyor. Sadece Foregin key oluştururken sorun yaşatıyor. Onu inceleyemedim bu sebeple foregin key leri yorum satırına aldım

**Comment by ashkan90** [comment]
Telegramda kabul edilmişti. Kapatıyorum
